# Generated by Django 3.1.5 on 2021-02-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210201_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashfoodmember',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cashfoodmember',
            name='code',
            field=models.CharField(default='0TRBWQYV', max_length=8, unique=True),
        ),
    ]
