# Generated by Django 3.1.5 on 2021-02-02 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20210201_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashfoodmember',
            name='code',
            field=models.CharField(default='Y0JV53CT', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='cashfoodmember',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
