# Generated by Django 3.1.5 on 2021-02-02 18:42

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210202_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashfoodmember',
            name='code',
            field=models.CharField(default='84QYZEHF', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='cashfoodmember',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
