# Generated by Django 3.1.5 on 2021-02-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210202_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashfoodmember',
            name='code',
            field=models.CharField(default='4S40EW4D', max_length=8, unique=True),
        ),
    ]
