# Generated by Django 3.1.5 on 2021-02-02 18:49

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210202_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashfoodmember',
            name='code',
            field=models.CharField(default=users.utils.get_random_code, max_length=8, unique=True),
        ),
    ]
