# Generated by Django 3.1.5 on 2021-02-28 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0012_auto_20210202_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashfoodmember',
            options={'verbose_name': 'Membre SBF', 'verbose_name_plural': 'Membres SBF'},
        ),
        migrations.AlterField(
            model_name='cashfoodmember',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True, verbose_name='Numero de Telephone'),
        ),
        migrations.AlterField(
            model_name='cashfoodmember',
            name='rugby_level',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='cashfoodmember',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
