# Generated by Django 3.1.5 on 2021-03-04 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210228_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affilie',
            options={'verbose_name': 'Affilie', 'verbose_name_plural': 'Affilies'},
        ),
        migrations.RenameField(
            model_name='cashfoodmember',
            old_name='is_member',
            new_name='is_eligible',
        ),
        migrations.AddField(
            model_name='cashfoodmember',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.cashfoodmember'),
        ),
    ]
