# Generated by Django 3.1.5 on 2021-03-04 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0014_auto_20210304_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_parrain', models.CharField(max_length=20, unique=True, verbose_name='Code Parrain')),
            ],
            options={
                'verbose_name': 'Code Parrain',
                'verbose_name_plural': 'Codes Parrains',
            },
        ),
        migrations.RenameModel(
            old_name='CashFoodMember',
            new_name='SBFMember',
        ),
        migrations.DeleteModel(
            name='Affilie',
        ),
        migrations.AddField(
            model_name='codes',
            name='sbfmember',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.sbfmember'),
        ),
    ]
