# Generated by Django 3.1.5 on 2021-03-05 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210305_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sbfmember',
            name='is_eligible',
        ),
    ]
