# Generated by Django 3.1.5 on 2021-05-03 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_sbfmember_is_eligible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codes',
            name='sbfmember',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.sbfmember', verbose_name='Utilisateur'),
        ),
    ]
