# Generated by Django 3.1.5 on 2021-05-05 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210503_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du Niveau')),
                ('prerequisite', models.IntegerField(unique=True, verbose_name="Nombre D'affilie a avoir")),
            ],
        ),
        migrations.CreateModel(
            name='Gain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='food.png', upload_to='pics/')),
                ('title', models.CharField(max_length=255, verbose_name='designation')),
                ('description', models.TextField()),
                ('matrice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.matrice')),
            ],
        ),
        migrations.CreateModel(
            name='Assignement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received', models.BooleanField(default=False, verbose_name='A recu son gain')),
                ('date_of_receipt', models.DateField(null=True, verbose_name='Date de Reception')),
                ('matrice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.matrice')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.sbfmember')),
            ],
        ),
    ]
